-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 19:18:38 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ABP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ABP` ;

-- -----------------------------------------------------
-- Schema ABP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ABP` DEFAULT CHARACTER SET utf8 ;
USE `ABP` ;

-- -----------------------------------------------------
-- Table `ABP`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `ABP`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `maxPlazas` INT NULL,
  PRIMARY KEY (`idActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`Ejercicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`Ejercicio` ;

CREATE TABLE IF NOT EXISTS `ABP`.`Ejercicio` (
  `idEjercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEjercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`TablaEjercicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`TablaEjercicio` ;

CREATE TABLE IF NOT EXISTS `ABP`.`TablaEjercicio` (
  `idTablaEjercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `dificultad` VARCHAR(45) NULL,
  `esPersonalizada` TINYINT(1) NULL,
  PRIMARY KEY (`idTablaEjercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `ABP`.`Usuario` (
  `dniUsuario` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tipo` VARCHAR(1) NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`dniUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`RelacionEjercicioTabla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`RelacionEjercicioTabla` ;

CREATE TABLE IF NOT EXISTS `ABP`.`RelacionEjercicioTabla` (
  `idEjercicio` INT NOT NULL,
  `idTablaEjercicio` INT NOT NULL,
  PRIMARY KEY (`idTablaEjercicio`, `idEjercicio`),
  INDEX `TablaAsociada_idx` (`idTablaEjercicio` ASC),
  CONSTRAINT `EjercicioAsociado.LinkerEjercicioTabla`
    FOREIGN KEY (`idEjercicio`)
    REFERENCES `ABP`.`Ejercicio` (`idEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TablaAsociada.LinkerEjercicioTabla`
    FOREIGN KEY (`idTablaEjercicio`)
    REFERENCES `ABP`.`TablaEjercicio` (`idTablaEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`RelacionTablaUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`RelacionTablaUsuario` ;

CREATE TABLE IF NOT EXISTS `ABP`.`RelacionTablaUsuario` (
  `idTablaEjercicio` INT NOT NULL,
  `dniUsuario` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idTablaEjercicio`, `dniUsuario`),
  INDEX `UsuarioAsociado_idx` (`dniUsuario` ASC),
  CONSTRAINT `TablaAsociada.LinkerTablaUsuario`
    FOREIGN KEY (`idTablaEjercicio`)
    REFERENCES `ABP`.`TablaEjercicio` (`idTablaEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UsuarioAsociado.LinkerTablaUsuario`
    FOREIGN KEY (`dniUsuario`)
    REFERENCES `ABP`.`Usuario` (`dniUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`SesionIndividual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`SesionIndividual` ;

CREATE TABLE IF NOT EXISTS `ABP`.`SesionIndividual` (
  `dniUsuario` VARCHAR(9) NOT NULL,
  `idTablaEjercicio` INT NOT NULL,
  `fecha` DATETIME NULL,
  `comentarioGeneral` VARCHAR(200) NULL,
  `idSesionIndividual` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idSesionIndividual`),
  INDEX `TablaAsociada_idx` (`idTablaEjercicio` ASC),
  CONSTRAINT `UsuarioAsociado`
    FOREIGN KEY (`dniUsuario`)
    REFERENCES `ABP`.`Usuario` (`dniUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TablaAsociada`
    FOREIGN KEY (`idTablaEjercicio`)
    REFERENCES `ABP`.`TablaEjercicio` (`idTablaEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`Comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`Comentario` ;

CREATE TABLE IF NOT EXISTS `ABP`.`Comentario` (
  `idEjercicio` INT NOT NULL,
  `idSesionIndividual` INT NOT NULL,
  `anotacion` VARCHAR(200) NULL,
  PRIMARY KEY (`idEjercicio`, `idSesionIndividual`),
  INDEX `SesionAsociada_idx` (`idSesionIndividual` ASC),
  CONSTRAINT `EjercicioAsociado.Comentario`
    FOREIGN KEY (`idEjercicio`)
    REFERENCES `ABP`.`Ejercicio` (`idEjercicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SesionAsociada.Comentario`
    FOREIGN KEY (`idSesionIndividual`)
    REFERENCES `ABP`.`SesionIndividual` (`idSesionIndividual`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`SesionActividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`SesionActividad` ;

CREATE TABLE IF NOT EXISTS `ABP`.`SesionActividad` (
  `idActividad` INT NULL,
  `idSesionActividad` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`idSesionActividad`),
  CONSTRAINT `ActividadAsociada.SesionActividad`
    FOREIGN KEY (`idActividad`)
    REFERENCES `ABP`.`Actividad` (`idActividad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ABP`.`RelacionUsuarioSesionactividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ABP`.`RelacionUsuarioSesionactividad` ;

CREATE TABLE IF NOT EXISTS `ABP`.`RelacionUsuarioSesionactividad` (
  `dniUsuario` VARCHAR(9) NOT NULL,
  `idSesionActividad` INT NOT NULL,
  PRIMARY KEY (`dniUsuario`, `idSesionActividad`),
  INDEX `SesionActividadAsociada_idx` (`idSesionActividad` ASC),
  CONSTRAINT `UsuarioAsociado.Reserva`
    FOREIGN KEY (`dniUsuario`)
    REFERENCES `ABP`.`Usuario` (`dniUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SesionActividadAsociada.Reserva`
    FOREIGN KEY (`idSesionActividad`)
    REFERENCES `ABP`.`SesionActividad` (`idSesionActividad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
